---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
library(RColorBrewer)
library(flexdashboard)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

data("rest_inspec")

#filter to just see Chelsea Restaurants
chelsea_rest = 
  rest_inspec %>% 
  filter(zipcode == 10001) %>% 
  mutate(
    inspection_date = as.Date(inspection_date, format = '%Y-%m-%d')
  )
```

Column {data-width=550}
-----------------------------------------------------------------------

### Chart A

```{r echo = FALSE}
chelsea_rest %>% 
  filter(cuisine_description=="Café/Coffee/Tea",
         !is.na(score)) %>% 
  distinct(dba, inspection_date, score) %>% 
  mutate(
    dba = if_else(dba == "CENTER PLATE- CONCOURSE CAFE-JACOB K JAVITS CONVENTION CENTER", "CENTER PLATE", dba)
  ) %>% 
  plot_ly(y = ~score, color = ~dba, type="box", colors = "viridis", text=~inspection_date) %>% 
    layout(showlegend = FALSE,
           title = "Distribution of Scores by Cafes in Chelsea",
           xaxis = list(title = 'Cafe'), 
           yaxis = list(title = 'Score'))

```

Column {.tabset data-width=450}
-----------------------------------------------------------------------

### Chart B

```{r echo = FALSE}
chelsea_rest %>% 
  filter(critical_flag == "Critical") %>% 
  count(violation_code, violation_description) %>% 
  filter (n > 0) %>% 
  mutate(violation_code = fct_reorder(violation_code, n)) %>% 
  plot_ly(x = ~violation_code, y = ~n, color = ~violation_code, type = "bar", 
          text = ~violation_description, colors = "viridis") %>% 
    layout(title = "Number of Critical Violation Codes in Chelsea Restaurants",
           xaxis = list(title = 'Violation Codes (with description)'), 
           yaxis = list(title = 'Number of Instances (n)'))
```

### Chart C

```{r echo = FALSE}
numCols = chelsea_rest %>% 
  filter(cuisine_description == "Pizza") %>% 
  distinct(dba) %>% 
  nrow()

mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(numCols)

chelsea_rest %>% 
  filter(cuisine_description == "Pizza", !is.na(score)) %>% 
  distinct(dba, inspection_date, score) %>% 
  arrange(inspection_date) %>% 
  plot_ly(
    x = ~inspection_date, y = ~score, type = "scatter", mode = "markers+lines", color = ~dba, colors = mycolors, alpha = 0.6
  ) %>% 
    layout(legend = list(orientation = 'h'),
           title = "Score Trends for Pizza Restaurants in Chelsea",
           xaxis = list(title = 'Date of Inspection'), 
           yaxis = list(title = 'Score'))
```

